using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//***********************************************************
//  委員長が考えた簡単ステージ１－２３４５候補
//***********************************************************

public class Stage1_2 : MonoBehaviour
{
    public static EnemyData[] enemydatas = new EnemyData[] {
//***********************************************************
//  Phase1
//***********************************************************
 //右から  ３体　まっすぐ
        new EnemyData(){
            name = "enemy01",
            phase = Phase.phase1,
            StartPosX = 12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 1,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy02",
            phase = Phase.phase1,
            StartPosX = 12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 1,
            sideNo = 2,
            AppearanceTime = 1,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy03",
            phase = Phase.phase1,
            StartPosX = 12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 1,
            sideNo = 2,
            AppearanceTime = 2,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
             NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

//左から３体まっすぐ
 new EnemyData(){
            name = "enemy04",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 4,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy05",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 1,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy06",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 2,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
             NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

//***********************************************************
//  Phase2
//***********************************************************
    
//下から一気にでます！！
//少し上で横一列
        new EnemyData(){
            name = "enemy07",
            phase = Phase.phase2,
            StartPosX = 0,
            StartPosY = -8,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 0f,
            EntryPosY = -4,
            sideNo = 1,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

          new EnemyData(){
            name = "enemy08",
            phase = Phase.phase2,
            StartPosX = -4,
            StartPosY = -8,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = -4f,
            EntryPosY = -4,
            sideNo = 1,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

           new EnemyData(){
            name = "enemy09",
            phase = Phase.phase2,
            StartPosX = 4,
            StartPosY = -8,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 4,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 4f,
            EntryPosY = -4,
            sideNo = 1,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

 //遅れてくるよ！
       new EnemyData(){
            name = "enemy10",
            phase = Phase.phase2,
            StartPosX = -2,
            StartPosY = -8,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = -2f,
            EntryPosY = -4,
            sideNo = 1,
            AppearanceTime = 2,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

     new EnemyData(){
            name = "enemy11",
            phase = Phase.phase2,
            StartPosX = 2,
            StartPosY = -8,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 2f,
            EntryPosY = -4,
            sideNo = 1,
            AppearanceTime = 2,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

//***********************************************************
//  Phase3
//***********************************************************
   //右から一気にでるよ！！
   //左のほうに縦一列
        new EnemyData(){
            name = "enemy12",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = 2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

         new EnemyData(){
            name = "enemy13",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 1,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

        new EnemyData(){
            name = "enemy14",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = 0,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 0,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

         new EnemyData(){
            name = "enemy15",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = -1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = -1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = -1,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

         new EnemyData(){
            name = "enemy16",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = -1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = -2,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

 //左から
            new EnemyData(){
            name = "enemy23",
            phase = Phase.phase3,
            StartPosX = -12,
            StartPosY = 2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

          new EnemyData(){
            name = "enemy24",
            phase = Phase.phase3,
            StartPosX = -12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = 1,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

         new EnemyData(){
            name = "enemy25",
            phase = Phase.phase3,
            StartPosX = -12,
            StartPosY = 0,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = 0,
            sideNo = 4,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

         new EnemyData(){
            name = "enemy26",
            phase = Phase.phase3,
            StartPosX = -12,
            StartPosY = -1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = -1,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -1,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
   new EnemyData(){
            name = "enemy27",
            phase = Phase.phase3,
            StartPosX = -12,
            StartPosY = -2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 0,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01


//<<<<<<<<<<<<<<<<
//右から  ３体　まっすぐ
        new EnemyData(){
            name = "enemy40",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 1,
            sideNo = 0,
            AppearanceTime = 10,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy41",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 1,
            sideNo = 0,
            AppearanceTime = 10,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy42",
            phase = Phase.phase3,
            StartPosX = 12,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 1,
            sideNo = 0,
            AppearanceTime = 10,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

//***********************************************************
//  Phase4
//***********************************************************
           new EnemyData(){
            name = "enemy17",
            phase = Phase.phase4,
            StartPosX = 12,
            StartPosY = 2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

         new EnemyData(){
            name = "enemy18",
            phase = Phase.phase4,
            StartPosX = 12,
            StartPosY = 2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

        new EnemyData(){
            name = "enemy19",
            phase = Phase.phase4,
            StartPosX = 12,
            StartPosY = 2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 8,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

   //左から３体まっすぐ
 new EnemyData(){
            name = "enemy20",
            phase = Phase.phase4,
            StartPosX = -12,
            StartPosY = -2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 4,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy21",
            phase = Phase.phase4,
            StartPosX = -12,
            StartPosY = -2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 4,
            TargetPosY = -1,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 3,
            Data1 = 3,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy22",
            phase = Phase.phase4,
            StartPosX = -12,
            StartPosY = -2,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 4,
            TargetPosY = -3,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
             NextStep1 = 3,
            Data1 = 5,　　　　//state３速度
            NextStep2 = 5,
            Data2 = 10,
            NextStep3 = 4,
            Data3 = 5,
            NextStep4 = -1,
            NextStep5 = -1
        },  // enemy01

//***********************************************************
//  Phase5
//***********************************************************
         new EnemyData(){
            name = "enemy27",
            phase = Phase.phase5,
            StartPosX = 11,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 1,
            FirstPosY = -3,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01


         new EnemyData(){
            name = "enemy23",
            phase = Phase.phase5,
            StartPosX = 12,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = -3,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 1,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01
          new EnemyData(){
            name = "enemy24",
            phase = Phase.phase5,
            StartPosX = 14,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = -3,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 2,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01
            new EnemyData(){
            name = "enemy25",
            phase = Phase.phase5,
            StartPosX = 16,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 7,
            FirstPosY = -3,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 3,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01

      new EnemyData(){
            name = "enemy26",
            phase = Phase.phase5,
            StartPosX = 18,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 9,
            FirstPosY = -3,
            FirstPosZ = 0,
            TargetPosX = 4,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 4,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01


        new EnemyData(){
            name = "enemy28",
            phase = Phase.phase5,
            StartPosX = 12,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = -5,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 1,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01
          new EnemyData(){
            name = "enemy29",
            phase = Phase.phase5,
            StartPosX = 14,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = -5,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 2,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01
            new EnemyData(){
            name = "enemy30",
            phase = Phase.phase5,
            StartPosX = 16,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 7,
            FirstPosY = -5,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = -2,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 0,
            AppearanceTime = 3,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextStep1 = 1,
            Data1 = 5,
           NextStep2 = 3,
            Data2 = 5,
            NextStep3 = 5,
            Data3 = 5,
            NextStep4 = 4,
            Data4 = 5,
            NextStep5 = -1
        },  // enemy01

    };
};
