using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Stage11 : MonoBehaviour
{
    public static EnemyData[] enemydatas = new EnemyData[]{
//***********************************************************
//  Phase1
//***********************************************************
        new EnemyData(){
            name = "enemy01",
            phase = Phase.phase1,
            StartPosX = 12,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 2,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 3,
            Data1 = 3,
            NextState2 = 4,
            Data2 = 5,
            NextState3 = -1,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy01
        new EnemyData(){
            name = "enemy02",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -1,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -2,
            sideNo = 4,
            AppearanceTime = 1,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 3,
            Data1 = 3,
            NextState2 = 4,
            Data2 = 5,
            NextState3 = -1,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy02
        new EnemyData(){
            name = "enemy03",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = 3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = 2,
            sideNo = 4,
            AppearanceTime = 2,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 3,
            Data1 = 3,
            NextState2 = 4,
            Data2 = 5,
            NextState3 = -1,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy03
        new EnemyData(){
            name = "enemy04",
            phase = Phase.phase1,
            StartPosX = 12,
            StartPosY = -3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 1,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = -2,
            sideNo = 2,
            AppearanceTime = 3,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 3,
            Data1 = 3,
            NextState2 = 4,
            Data2 = 5,
            NextState3 = -1,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy04
        new EnemyData(){
            name = "enemy05",
            phase = Phase.phase1,
            StartPosX = 12,
            StartPosY = 0,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = 1,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 0,
            sideNo = 2,
            AppearanceTime = 4,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 3,
            Data1 = 3,
            NextState2 = 4,
            Data2 = 5,
            NextState3 = -1,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy05
//***********************************************************
//  Phase2
//***********************************************************
        new EnemyData(){
            name = "enemy06",
            phase = Phase.phase2,
            StartPosX = -15,
            StartPosY = 10,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 1,
            FirstPosZ = 0,
            TargetPosX = 3,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = 4,
            EntryPosY = 4.2f,
            sideNo = 3,
            AppearanceTime = 1f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 7,
            NextState2 = 3,
            Data2 = 3,
            NextState3 = 4,
            Data3 = 6,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy06
        new EnemyData(){
            name = "enemy07",
            phase = Phase.phase2,
            StartPosX = -14,
            StartPosY = 9,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = 3,
            TargetPosY = 0,
            TargetPosZ = 0,
            AppearanceTime = 2f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 7,
            NextState2 = 3,
            Data2 = 3,
            NextState3 = 4,
            Data3 = 6,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy07
        new EnemyData(){
            name = "enemy08",
            phase = Phase.phase2,
            StartPosX = -13,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = -1,
            FirstPosZ = 0,
            TargetPosX = 3,
            TargetPosY = -1,
            TargetPosZ = 0,
            AppearanceTime = 3f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 7,
            NextState2 = 3,
            Data2 = 3,
            NextState3 = 4,
            Data3 = 6,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy08
//***********************************************************
        new EnemyData(){
            name = "enemy09",
            phase = Phase.phase2,
            StartPosX = 15,
            StartPosY = 10,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = 1,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 1,
            TargetPosZ = 0,
            EntryPosX = -4,
            EntryPosY = 4.2f,
            sideNo = 3,
            AppearanceTime = 6f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 7,
            NextState2 = 3,
            Data2 = 3,
            NextState3 = 4,
            Data3 = 6,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy09
        new EnemyData(){
            name = "enemy10",
            phase = Phase.phase2,
            StartPosX = 14,
            StartPosY = 9,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 0,
            TargetPosZ = 0,
            AppearanceTime = 7f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 7,
            NextState2 = 3,
            Data2 = 3,
            NextState3 = 4,
            Data3 = 6,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy10
        new EnemyData(){
            name = "enemy11",
            phase = Phase.phase2,
            StartPosX = 13,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = -1,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = -1,
            TargetPosZ = 0,
            AppearanceTime = 8f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 7,
            NextState2 = 3,
            Data2 = 3,
            NextState3 = 4,
            Data3 = 6,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy11
//***********************************************************
//  Phase3
//***********************************************************
        new EnemyData(){
            name = "enemy12",
            phase = Phase.phase3,
            StartPosX = 11,
            StartPosY = -12,
            StartPosZ = 0,
            FirstPosX = 4,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = 8.1f,
            EntryPosY = 0.2f,
            sideNo = 2,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy12
        new EnemyData(){
            name = "enemy13",
            phase = Phase.phase3,
            StartPosX = 11,
            StartPosY = -12,
            StartPosZ = 0,
            FirstPosX = 4,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = -1,
            TargetPosY = -1,
            TargetPosZ = 0,
            AppearanceTime = 0.5f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy13
        new EnemyData(){
            name = "enemy14",
            phase = Phase.phase3,
            StartPosX = 11,
            StartPosY = -12,
            StartPosZ = 0,
            FirstPosX = 4,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = -2,
            TargetPosZ = 0,
            AppearanceTime = 1,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy14
        new EnemyData(){
            name = "enemy15",
            phase = Phase.phase3,
            StartPosX = 11,
            StartPosY = -12,
            StartPosZ = 0,
            FirstPosX = 4,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = 1,
            TargetPosY = -1,
            TargetPosZ = 0,
            AppearanceTime = 1.5f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy15
//***********************************************************
        new EnemyData(){
            name = "enemy16",
            phase = Phase.phase3,
            StartPosX = -11,
            StartPosY = 12,
            StartPosZ = 0,
            FirstPosX = -4,
            FirstPosY = -2,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 0,
            TargetPosZ = 0,
            EntryPosX = -8.1f,
            EntryPosY = -0.2f,
            sideNo = 4,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy16
        new EnemyData(){
            name = "enemy17",
            phase = Phase.phase3,
            StartPosX = -11,
            StartPosY = 12,
            StartPosZ = 0,
            FirstPosX = -4,
            FirstPosY = -2,
            FirstPosZ = 0,
            TargetPosX = 1,
            TargetPosY = 1,
            TargetPosZ = 0,
            AppearanceTime = 0.5f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy17
        new EnemyData(){
            name = "enemy18",
            phase = Phase.phase3,
            StartPosX = -11,
            StartPosY = 12,
            StartPosZ = 0,
            FirstPosX = -4,
            FirstPosY = -2,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = 2,
            TargetPosZ = 0,
            AppearanceTime = 1.0f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy18
        new EnemyData(){
            name = "enemy19",
            phase = Phase.phase3,
            StartPosX = -11,
            StartPosY = 12,
            StartPosZ = 0,
            FirstPosX = -4,
            FirstPosY = -2,
            FirstPosZ = 0,
            TargetPosX = -1,
            TargetPosY = 1,
            TargetPosZ = 0,
            AppearanceTime = 1.5f,
            model = "koa",
            category = EnemyCategory.typeNone,
            Size = 5.0f,
            NextState1 = 1,
            Data1 = 5,
            NextState2 = 5,
            Data2 = 1,
            NextState3 = 3,
            Data3 = 5,
            NextState4 = 4,
            Data4 = 5,
            NextState5 = -1
        },  // enemy19
//***********************************************************
//  Phase4
//***********************************************************
        new EnemyData(){
            name = "enemy20",
            phase = Phase.phase4,
            StartPosX = -4,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = -3,
            TargetPosZ = 0,
            EntryPosX = -3,
            EntryPosY = 4.2f,
            sideNo = 3,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 3,
            Data1 = 4,
            NextState2 = 4,
            Data2 = 6,
            NextState3 = -1,
            NextState4 = -1,
            NextState5 = -1
        },  // enemy20
        new EnemyData(){
            name = "enemy21",
            phase = Phase.phase4,
            StartPosX = -3,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = -3,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 0.3f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy21
        new EnemyData(){
            name = "enemy22",
            phase = Phase.phase4,
            StartPosX = -2,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 0.6f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy22
        new EnemyData(){
            name = "enemy23",
            phase = Phase.phase4,
            StartPosX = -1,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = -1,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 0.9f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy23
        new EnemyData(){
            name = "enemy24",
            phase = Phase.phase4,
            StartPosX = 0,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 1.2f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy24
        new EnemyData(){
            name = "enemy25",
            phase = Phase.phase4,
            StartPosX = 1,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = 1,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 1.5f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy25
        new EnemyData(){
            name = "enemy26",
            phase = Phase.phase4,
            StartPosX = 2,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 1.8f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy26
        new EnemyData(){
            name = "enemy27",
            phase = Phase.phase4,
            StartPosX = 3,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = 3,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 2.1f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy27
        new EnemyData(){
            name = "enemy28",
            phase = Phase.phase4,
            StartPosX = 4,
            StartPosY = 8,
            StartPosZ = 0,
            FirstPosX = 5,
            FirstPosY = 2,
            FirstPosZ = 0,
            TargetPosX = 4,
            TargetPosY = -3,
            TargetPosZ = 0,
            AppearanceTime = 2.4f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 5.0f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },  // enemy28
//***********************************************************
        //new EnemyData(){
        //    name = "enemy29",
        //    phase = Phase.phase4,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 0,
        //    FirstPosY = 0,
        //    FirstPosZ = 0,
        //    TargetPosX = 2,
        //    TargetPosY = 0,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 8.0f,
        //    model = "koa",
        //    category = EnemyCategory.type1,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy29
        //new EnemyData(){
        //    name = "enemy30",
        //    phase = Phase.phase4,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 0,
        //    FirstPosY = 0,
        //    FirstPosZ = 0,
        //    TargetPosX = 3,
        //    TargetPosY = 0,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 8.3f,
        //    model = "koa",
        //    category = EnemyCategory.type1,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy30
        //new EnemyData(){
        //    name = "enemy31",
        //    phase = Phase.phase4,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 0,
        //    FirstPosY = 0,
        //    FirstPosZ = 0,
        //    TargetPosX = 4,
        //    TargetPosY = 0,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 8.6f,
        //    model = "koa",
        //    category = EnemyCategory.type1,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy31
        //new EnemyData(){
        //    name = "enemy32",
        //    phase = Phase.phase4,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 0,
        //    FirstPosY = 0,
        //    FirstPosZ = 0,
        //    TargetPosX = 5,
        //    TargetPosY = 0,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 8.9f,
        //    model = "koa",
        //    category = EnemyCategory.type1,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy32
        //new EnemyData(){
        //    name = "enemy33",
        //    phase = Phase.phase4,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 3,
        //    FirstPosY = -3,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = -4,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 9.2f,
        //    model = "koa",
        //    category = EnemyCategory.type1,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy33
        //new EnemyData(){
        //    name = "enemy34",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 3,
        //    FirstPosY = -3,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = -3,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 9.5f,
        //    model = "koa",
        //    category = EnemyCategory.type2,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy34
        //new EnemyData(){
        //    name = "enemy35",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 3,
        //    FirstPosY = -3,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = -2,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 9.8f,
        //    model = "koa",
        //    category = EnemyCategory.type2,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy35
        //new EnemyData(){
        //    name = "enemy36",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 3,
        //    FirstPosY = -3,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = -1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 10.1f,
        //    model = "koa",
        //    category = EnemyCategory.type2,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy36
        //new EnemyData(){
        //    name = "enemy37",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 3,
        //    FirstPosY = -3,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = 0,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 10.4f,
        //    model = "koa",
        //    category = EnemyCategory.type2,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy37


//***********************************************************
//  Phase5
//***********************************************************
        //new EnemyData(){
        //    name = "enemy38",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 3,
        //    FirstPosY = -3,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 16,
        //    model = "koa",
        //    category = EnemyCategory.type2,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy38
        //new EnemyData(){
        //    name = "enemy39",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = 3,
        //    FirstPosY = -3,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = 2,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 17,
        //    model = "koa",
        //    category = EnemyCategory.type2,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy39
        //new EnemyData(){
        //    name = "enemy40",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = -4,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 18,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy40
        //new EnemyData(){
        //    name = "enemy41",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = -3,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 19,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy41
        //new EnemyData(){
        //    name = "enemy42",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = -2,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 20,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy42
        //new EnemyData(){
        //    name = "enemy43",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = -1,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 21,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy43
        //new EnemyData(){
        //    name = "enemy44",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = 0,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 22,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy44
        //new EnemyData(){
        //    name = "enemy45",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = 1,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 23,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy45
        //new EnemyData(){
        //    name = "enemy46",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = 2,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 24,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy46
        //new EnemyData(){
        //    name = "enemy47",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = 3,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 25,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy47
        //new EnemyData(){
        //    name = "enemy48",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = 4,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 26,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy48
        //new EnemyData(){
        //    name = "enemy49",
        //    phase = Phase.phase5,
        //    StartPosX = 12,
        //    StartPosY = 3,
        //    StartPosZ = 0,
        //    FirstPosX = -3,
        //    FirstPosY = -2,
        //    FirstPosZ = 0,
        //    TargetPosX = 5,
        //    TargetPosY = 1,
        //    TargetPosZ = 0,
        //    EntryPosX = 0,
        //    EntryPosY = 0,
        //    sideNo = 0,
        //    AppearanceTime = 27,
        //    model = "koa",
        //    category = EnemyCategory.type3,
        //    Size = 5.0f,
        //    NextState1 = 1,
        //    NextState2 = 2,
        //    NextState3 = 3,
        //    NextState4 = 4,
        //    NextState5 = -1
        //},  // enemy49

    };
}



//new EnemyData()
//{
//    name = "enemy21",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 5,
//            FirstPosY = 2,
//            FirstPosZ = 0,
//            TargetPosX = -1,
//            TargetPosY = -3,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 0.3f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy21
//        new EnemyData()
//{
//    name = "enemy22",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 5,
//            FirstPosY = 2,
//            FirstPosZ = 0,
//            TargetPosX = 0,
//            TargetPosY = -3,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 0.6f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy22
//        new EnemyData()
//{
//    name = "enemy23",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 0,
//            TargetPosY = 2,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 0.9f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy23
//        new EnemyData()
//{
//    name = "enemy24",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 1,
//            TargetPosY = 2,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 1.2f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy24
//        new EnemyData()
//{
//    name = "enemy25",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 2,
//            TargetPosY = 2,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 1.5f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy25
//        new EnemyData()
//{
//    name = "enemy26",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 3,
//            TargetPosY = 2,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 1.8f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy26
//        new EnemyData()
//{
//    name = "enemy27",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 0,
//            TargetPosY = 0,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 6.0f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy27
//        new EnemyData()
//{
//    name = "enemy28",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 1,
//            TargetPosY = 0,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 6.3f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy28
//        new EnemyData()
//{
//    name = "enemy29",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 2,
//            TargetPosY = 0,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 6.6f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy29
//        new EnemyData()
//{
//    name = "enemy30",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 3,
//            TargetPosY = 0,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 6.9f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy30
//        new EnemyData()
//{
//    name = "enemy31",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 4,
//            TargetPosY = 0,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 7.2f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy31
//        new EnemyData()
//{
//    name = "enemy32",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 0,
//            FirstPosY = 0,
//            FirstPosZ = 0,
//            TargetPosX = 5,
//            TargetPosY = 0,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 7.5f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy32
//        new EnemyData()
//{
//    name = "enemy33",
//            phase = Phase.phase4,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 3,
//            FirstPosY = -3,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = -4,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 7.8f,
//            model = "koa",
//            category = EnemyCategory.type1,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy33

////***********************************************************
////  Phase5
////***********************************************************
//        new EnemyData()
//{
//    name = "enemy34",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 3,
//            FirstPosY = -3,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = -3,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 12,
//            model = "koa",
//            category = EnemyCategory.type2,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy34
//        new EnemyData()
//{
//    name = "enemy35",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 3,
//            FirstPosY = -3,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = -2,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 13,
//            model = "koa",
//            category = EnemyCategory.type2,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy35
//        new EnemyData()
//{
//    name = "enemy36",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 3,
//            FirstPosY = -3,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = -1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 14,
//            model = "koa",
//            category = EnemyCategory.type2,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy36
//        new EnemyData()
//{
//    name = "enemy37",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 3,
//            FirstPosY = -3,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = 0,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 15,
//            model = "koa",
//            category = EnemyCategory.type2,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy37
//        new EnemyData()
//{
//    name = "enemy38",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 3,
//            FirstPosY = -3,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 16,
//            model = "koa",
//            category = EnemyCategory.type2,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy38
//        new EnemyData()
//{
//    name = "enemy39",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = 3,
//            FirstPosY = -3,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = 2,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 17,
//            model = "koa",
//            category = EnemyCategory.type2,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy39
//        new EnemyData()
//{
//    name = "enemy40",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = -4,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 18,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy40
//        new EnemyData()
//{
//    name = "enemy41",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = -3,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 19,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy41
//        new EnemyData()
//{
//    name = "enemy42",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = -2,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 20,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy42
//        new EnemyData()
//{
//    name = "enemy43",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = -1,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 21,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy43
//        new EnemyData()
//{
//    name = "enemy44",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = 0,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 22,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy44
//        new EnemyData()
//{
//    name = "enemy45",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = 1,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 23,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy45
//        new EnemyData()
//{
//    name = "enemy46",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = 2,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 24,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy46
//        new EnemyData()
//{
//    name = "enemy47",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = 3,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 25,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy47
//        new EnemyData()
//{
//    name = "enemy48",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = 4,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 26,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy48
//        new EnemyData()
//{
//    name = "enemy49",
//            phase = Phase.phase5,
//            StartPosX = 12,
//            StartPosY = 3,
//            StartPosZ = 0,
//            FirstPosX = -3,
//            FirstPosY = -2,
//            FirstPosZ = 0,
//            TargetPosX = 5,
//            TargetPosY = 1,
//            TargetPosZ = 0,
//            EntryPosX = 0,
//            EntryPosY = 0,
//            sideNo = 0,
//            AppearanceTime = 27,
//            model = "koa",
//            category = EnemyCategory.type3,
//            Size = 5.0f,
//            NextState1 = 1,
//            NextState2 = 2,
//            NextState3 = 3,
//            NextState4 = 4,
//            NextState5 = -1
//        },  // enemy49

