using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Stage12 : MonoBehaviour
{
    public static EnemyData[] enemydatas = new EnemyData[]{
//***********************************************************
        new EnemyData(){
            name = "enemy01",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -4,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 3,
            EntryPosY = -4.5f,
            sideNo = 1,
            AppearanceTime = 0.0f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
        new EnemyData(){
            name = "enemy02",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -3,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 0,
            EntryPosY = 0,
            sideNo = 0,
            AppearanceTime = 0.1f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
        new EnemyData(){
            name = "enemy03",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -2,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 0,
            EntryPosY = 0,
            sideNo = 0,
            AppearanceTime = 0.2f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
        new EnemyData(){
            name = "enemy04",
            phase = Phase.phase1,
            StartPosX = -12,
            StartPosY = -3,
            StartPosZ = 0,
            FirstPosX = 3,
            FirstPosY = 0,
            FirstPosZ = 0,
            TargetPosX = -1,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 0,
            EntryPosY = 0,
            sideNo = 0,
            AppearanceTime = 0.3f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
//***********************************************************
        new EnemyData(){
            name = "enemy05",
            phase = Phase.phase2,
            StartPosX = -11,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = 1,
            FirstPosZ = 0,
            TargetPosX = 0,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = -8.4f,
            EntryPosY = 2,
            sideNo = 4,
            AppearanceTime = 0,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
        new EnemyData(){
            name = "enemy06",
            phase = Phase.phase2,
            StartPosX = -11,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = 1,
            FirstPosZ = 0,
            TargetPosX = 1,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 0,
            EntryPosY = 0,
            sideNo = 0,
            AppearanceTime = 0.1f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
        new EnemyData(){
            name = "enemy07",
            phase = Phase.phase2,
            StartPosX = -11,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = 1,
            FirstPosZ = 0,
            TargetPosX = 2,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 0,
            EntryPosY = 0,
            sideNo = 0,
            AppearanceTime = 0.2f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
        new EnemyData(){
            name = "enemy08",
            phase = Phase.phase2,
            StartPosX = -11,
            StartPosY = 1,
            StartPosZ = 0,
            FirstPosX = -2,
            FirstPosY = 1,
            FirstPosZ = 0,
            TargetPosX = 3,
            TargetPosY = 2,
            TargetPosZ = 0,
            EntryPosX = 0,
            EntryPosY = 0,
            sideNo = 0,
            AppearanceTime = 0.3f,
            model = "koa",
            category = EnemyCategory.type1,
            Size = 0.2f,
            NextState1 = 1,
            NextState2 = 2,
            NextState3 = 3,
            NextState4 = 4,
            NextState5 = -1
        },
    };
}

